### ISSUE TITLE
나였으면

### ISSUE THREAD

**Issue by jurogrammer** [wndlsrnr1/project#37]
**작업 내용**
주인재였으면 어떻게 짰을 지 생각.

**Task**
- [ ] 200응답에선 ResponseEntity 제거 (어차피 다 200이라 번잡함)
- [ ] 커스텀 익셉션 정의
- [ ] controllerAdvice 적용
- [ ] redirect page -> 200 응답
